---
version: '2'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
